"""Initial InventCheck schema"""

from alembic import op
import sqlalchemy as sa

revision = "ab349f0de27e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("brand", sa.String(length=80), nullable=False),
        sa.Column("model_number", sa.String(length=80), nullable=False),
        sa.Column("upc", sa.String(length=14), nullable=False),
        sa.Column("gtin", sa.String(length=14), nullable=False),
        sa.Column("image_url", sa.String(length=300), nullable=False),
        sa.Column("provenance", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_products_provenance"), ["provenance"], unique=False)

    op.create_table(
        "retailers",
        sa.Column("id", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("website", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "retailer_listings",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("product_id", sa.String(length=80), nullable=False),
        sa.Column("retailer_id", sa.String(length=30), nullable=False),
        sa.Column("sku", sa.String(length=80), nullable=False),
        sa.Column("product_url", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["retailer_id"],
            ["retailers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("retailer_id", "sku"),
    )
    with op.batch_alter_table("retailer_listings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_retailer_listings_product_id"), ["product_id"], unique=False
        )

    op.create_table(
        "stores",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("retailer_id", sa.String(length=30), nullable=False),
        sa.Column("store_identifier", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("address", sa.String(length=200), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("zip_code", sa.String(length=5), nullable=False),
        sa.Column("latitude", sa.Double(), nullable=False),
        sa.Column("longitude", sa.Double(), nullable=False),
        sa.Column("provenance", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(
            ["retailer_id"],
            ["retailers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("retailer_id", "store_identifier", "provenance"),
    )
    op.create_table(
        "watchlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.String(length=80), nullable=False),
        sa.Column("target_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("zip_code", sa.String(length=5), nullable=False),
        sa.Column("radius", sa.Integer(), nullable=False),
        sa.Column("retailers", sa.JSON(), nullable=False),
        sa.Column("provenance", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_attempted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_successful_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("check_status", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("watchlist", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_watchlist_provenance"), ["provenance"], unique=False)

    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("watchlist_id", sa.Integer(), nullable=False),
        sa.Column("dedup_key", sa.String(length=250), nullable=False),
        sa.Column("message", sa.String(length=400), nullable=False),
        sa.Column("provenance", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("dismissed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["watchlist_id"], ["watchlist.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedup_key"),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_alerts_provenance"), ["provenance"], unique=False)

    op.create_table(
        "price_checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.String(length=80), nullable=False),
        sa.Column("listing_id", sa.String(length=100), nullable=False),
        sa.Column("store_id", sa.String(length=100), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("regular_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("inventory_status", sa.String(length=30), nullable=False),
        sa.Column("inventory_quantity", sa.Integer(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provenance", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["retailer_listings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("listing_id", "store_id", "observed_at"),
    )
    with op.batch_alter_table("price_checks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_price_checks_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_price_checks_observed_at"), ["observed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_price_checks_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_price_checks_provenance"), ["provenance"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("price_checks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_price_checks_provenance"))
        batch_op.drop_index(batch_op.f("ix_price_checks_product_id"))
        batch_op.drop_index(batch_op.f("ix_price_checks_observed_at"))
        batch_op.drop_index(batch_op.f("ix_price_checks_expires_at"))

    op.drop_table("price_checks")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_provenance"))

    op.drop_table("alerts")
    with op.batch_alter_table("watchlist", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watchlist_provenance"))

    op.drop_table("watchlist")
    op.drop_table("stores")
    with op.batch_alter_table("retailer_listings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_retailer_listings_product_id"))

    op.drop_table("retailer_listings")
    op.drop_table("retailers")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_products_provenance"))

    op.drop_table("products")
    # ### end Alembic commands ###
